### ISSUE TITLE
Error on OS2

### ISSUE THREAD

**Issue by Tellie** [manufino/eSchema#1]
Hi,

I wanne build this for good OS/2
Using gcc 9.2.0 and Qt v5.15.2
But i get this error:

../src/SheetView.cpp:142:28: error: 'class QMouseEvent' has no member named 'position
  142 |         m_originX = event->position().x();

Any ideaif this fixable.

Kind regards, TeLLie /2

**Comment by manufino** [comment]
Hi, this project requires QT 6 (or higher) to build.
This is a project in early development, It's not usable yet.
